export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';

// Question Actions
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const REMOVE_QUESTION_SUCCESS = 'REMOVE_QUESTION_SUCCESS';

// User Actions
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const GET_AUTH0_USER_SUCCESS = 'GET_AUTH0_USER_SUCCESS';
export const GET_AUTH0_USER_FAILURE = 'GET_AUTH0_USER_FAILURE';


export const REMOVE_PROFILE = 'REMOVE_PROFILE';

export const UPDATE_PROFILE_ADDRESS_SUCCESS = 'UPDATE_PROFILE_ADDRESS_SUCCESS';
export const UPDATE_PROFILE_ADDRESS_FAILURE = 'UPDATE_PROFILE_ADDRESS_FAILURE';

export const UPDATE_PROFILE_EDUCATION_SUCCESS = 'UPDATE_PROFILE_EDUCATION_SUCCESS';
export const ADD_PROFILE_EDUCATION_SUCCESS = 'ADD_PROFILE_EDUCATION_SUCCESS';
export const REMOVE_PROFILE_EDUCATION_SUCCESS = 'REMOVE_PROFILE_EDUCATION_SUCCESS';

export const UPDATE_PROFILE_EMPLOYMENT_SUCCESS = 'UPDATE_PROFILE_EMPLOYMENT_SUCCESS';
export const ADD_PROFILE_EMPLOYMENT_SUCCESS = 'ADD_PROFILE_EMPLOYMENT_SUCCESS';
export const REMOVE_PROFILE_EMPLOYMENT_SUCCESS = 'REMOVE_PROFILE_EMPLOYMENT_SUCCESS';

export const UPDATE_PROFILE_SKILLS_SUCCESS = 'UPDATE_PROFILE_SKILLS_SUCCESS';



export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';


// UI ACTIONS
export const PROFILE_SECTION_ENTERED = "PROFILE_SECTION_ENTERED";
export const LOGIN_PAGE_ENTERED = "LOGIN_PAGE_ENTERED";

