export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';

// Question Actions
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const REMOVE_QUESTION_SUCCESS = 'REMOVE_QUESTION_SUCCESS';

// Question Panel Actions
export const LOAD_QUESTION_PANELS_SUCCESS = 'LOAD_QUESTION_PANELS_SUCCESS';
export const ADD_QUESTION_PANEL_SUCCESS = 'ADD_QUESTION_PANEL_SUCCESS';
export const UPDATE_QUESTION_PANEL_SUCCESS = 'UPDATE_QUESTION_PANEL_SUCCESS';
export const REMOVE_QUESTION_PANEL_SUCCESS = 'REMOVE_QUESTION_PANEL_SUCCESS';

// Question Set Actions
export const LOAD_QUESTION_SETS_SUCCESS = 'LOAD_QUESTION_SETS_SUCCESS';
export const ADD_QUESTION_SET_SUCCESS = 'ADD_QUESTION_SET_SUCCESS';
export const UPDATE_QUESTION_SET_SUCCESS = 'UPDATE_QUESTION_SET_SUCCESS';
export const REMOVE_QUESTION_SET_SUCCESS = 'REMOVE_QUESTION_SET_SUCCESS';

// Question Grid Actions
export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
export const LOAD_QUESTION_ANSWERS_SUCCESS = 'LOAD_QUESTION_ANSWERS_SUCCESS';
export const CLEAR_QUESTION_ANSWERS = 'CLEAR_QUESTION_ANSWERS';

// User Actions
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const SET_PROFILE = 'SET_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';

export const UPDATE_PROFILE_ADDRESS_SUCCESS = 'UPDATE_PROFILE_ADDRESS_SUCCESS';
export const UPDATE_PROFILE_ADDRESS_FAILURE = 'UPDATE_PROFILE_ADDRESS_FAILURE';

export const UPDATE_PROFILE_EDUCATION_SUCCESS = 'UPDATE_PROFILE_EDUCATION_SUCCESS';
export const ADD_PROFILE_EDUCATION_SUCCESS = 'ADD_PROFILE_EDUCATION_SUCCESS';
export const REMOVE_PROFILE_EDUCATION_SUCCESS = 'REMOVE_PROFILE_EDUCATION_SUCCESS';

export const UPDATE_PROFILE_EMPLOYMENT_SUCCESS = 'UPDATE_PROFILE_EMPLOYMENT_SUCCESS';
export const ADD_PROFILE_EMPLOYMENT_SUCCESS = 'ADD_PROFILE_EMPLOYMENT_SUCCESS';
export const REMOVE_PROFILE_EMPLOYMENT_SUCCESS = 'REMOVE_PROFILE_EMPLOYMENT_SUCCESS';

export const UPDATE_PROFILE_SKILLS_SUCCESS = 'UPDATE_PROFILE_SKILLS_SUCCESS';

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const UPDATE_USERNAME_SUCCESS = 'UPDATE_USERNAME_SUCCESS';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';


// UI ACTIONS
export const PROFILE_SECTION_ENTERED = "PROFILE_SECTION_ENTERED";
export const ADMIN_QUESTION_PANEL_SELECTED = "ADMIN_QUESTION_PANEL_SELECTED";
export const ADMIN_QUESTION_SET_SELECTED = "ADMIN_QUESTION_SET_SELECTED";
export const LOGIN_PAGE_ENTERED = "LOGIN_PAGE_ENTERED";
export const SET_CURRENT_PANEL = "SET_CURRENT_PANEL";
export const PUSH_PANEL_HISTORY= "PUSH_PANEL_HISTORY";
export const POP_PANEL_HISTORY= "POP_PANEL_HISTORY";
export const CLEAR_PANEL_HISTORY= "CLEAR_PANEL_HISTORY";



