// Question Actions
export const TOGGLE_QUESTION = 'TOGGLE_QUESTION';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';

// Profile Actions
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';

export const UPDATE_PROFILE_ADDRESS_SUCCESS = 'UPDATE_PROFILE_ADDRESS_SUCCESS';
export const UPDATE_PROFILE_ADDRESS_FAILURE = 'UPDATE_PROFILE_ADDRESS_FAILURE';

export const UPDATE_PROFILE_EDUCATION_SUCCESS = 'UPDATE_PROFILE_EDUCATION_SUCCESS';
export const ADD_PROFILE_EDUCATION_SUCCESS = 'ADD_PROFILE_EDUCATION_SUCCESS';
export const REMOVE_PROFILE_EDUCATION_SUCCESS = 'REMOVE_PROFILE_EDUCATION_SUCCESS';

export const UPDATE_PROFILE_EMPLOYMENT_SUCCESS = 'UPDATE_PROFILE_EMPLOYMENT_SUCCESS';
export const ADD_PROFILE_EMPLOYMENT_SUCCESS = 'ADD_PROFILE_EMPLOYMENT_SUCCESS';
export const REMOVE_PROFILE_EMPLOYMENT_SUCCESS = 'REMOVE_PROFILE_EMPLOYMENT_SUCCESS';

export const UPDATE_PROFILE_SKILLS_SUCCESS = 'UPDATE_PROFILE_SKILLS_SUCCESS';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

export const PROFILE_SECTION_ENTERED = "PROFILE_SECTION_ENTERED";

